# Generated by Django 2.0.3 on 2018-03-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_text', '0002_vjtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vjtext',
            old_name='vltext',
            new_name='vjtext',
        ),
    ]
